name = "nanolink-v2"
compatibility_date = "2026-06-05"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "nanolink"
database_id = "26026c32-50fc-4be4-bf4e-230b4ca88787"
