name = "email-collector"
main = "worker.js"
compatibility_date = "2026-05-01"

[[kv_namespaces]]
binding = "EMAILS"
id = "51de4a09f5cc42b0a31e34d56b1a1500"
preview_id = "51de4a09f5cc42b0a31e34d56b1a1500"
